### PR TITLE
Contributing.md

### PR DESCRIPTION
**Pull request by HarryHeights**
I've created the contributor's guide. It's quite bulky and there maybe some elements you may not ideally need. You can take them out yourself or let me know and I will make those changes. This document should boost the influx of contributors.

### CODE REVIEW

**Review by iamSahdeep — COMMENTED** [review]
Hello @HarryHeights ,It looks good to me, but do you think we need  Code Contribution and Documentation. I just want people not to get confused with this much guidelines!

**Comment by HarryHeights** [comment]
I don't they will be confused. The guideline has sections for different kinds of contributors. So when a contributor sees the section that's related to his kind of contribution, he'll know what to do there. The code part is for people who want to make code contributions to the project. Maybe to fix a bug, or implement a new feature. We could remove that if you aren't accepting that kind of contribution.

**Comment by iamSahdeep** [comment]
@HarryHeights  I have done some changes and will merge soon after checks. Thank you for PR.

**Comment by HarryHeights** [comment]
Oh okay. No qualms.

**Comment by iamSahdeep** [comment]
strange error in travis but not relateded to PR. Merging anyway.

**Comment by HarryHeights** [comment]
Okay great.. Is the any other kind of written content or document you'd like to have. I'm on fire 🔥🔥 lately.

**Pull request merged**
